### PR TITLE
Videojs 5x companions

### PR DESCRIPTION
**Pull request by alex-phillips**
Companion ad support for the VideoJS version 5 branch

### CODE REVIEW

**Comment by massa84** [comment]
hi @alex-phillips could you please delete and recreate this PR ? 
I force pushed a commit to video.js5 branch and messed up the diff of you PR.

**Comment by Fetz** [comment]
Hi @alex-phillips, thank you for PR, can only fix the conflicts so we can merge. Cheers.

**Comment by alex-phillips** [comment]
@Fetz it looks like tests are failing on the videojs-5x branch (even without my changes)

**Comment by Fetz** [comment]
Hi @alex-phillips, I just run the test with the latests npm dependencies and is working, and in TravisCI is working. By the error looks you are using the old karma. Please run `npm update` or remove node_modules `rm -rf node_modules` and run `npm install`

**Comment by alex-phillips** [comment]
@Fetz That worked, sorry about that. Should be all up-to-date now.

**Comment by Fetz** [comment]
Hi @alex-phillips, thanks for the pull request. I will merge now to avoid more conflicts. If you have some time will be nice to include a new pull-request with a readme update explaining how to get the companions

**Pull request merged**
