### PR TITLE
Player pause race condition

### PR DESCRIPTION
**Pull request by alex-phillips**
There is a race condition that can occur when the VAST code attempts to call `pause` on the player, but the player has not loaded the video and began playing yet. This PR adds an interval that does not proceed until the player has actually been paused.

### CODE REVIEW

**Comment by massa84** [comment]
can you provide an example that triggers the race condition ?

**Comment by alex-phillips** [comment]
Here's a test URL: http://www.wootables.com/videojs-alex/bower_components/videojs/dist/examples/simple-embed/test.html

Note: this is code running WITHOUT this PR (so the ad plays over the video)

**Comment by alex-phillips** [comment]
Sorry, this PR was originally from the wrong branch. Only 1 file should be changed. Fixing now.

**Comment by alex-phillips** [comment]
@massa84 Are you able to confirm this issue with my test?

**Comment by massa84** [comment]
hi @alex-phillips , yes i've  confirmed your issue but I'll propose you an alternative solution (as I don't really like that 1ms interval approach)
can you verify that the branch [pause-race-condition-fix](/MailOnline/videojs-vast-vpaid/tree/pause-race-condition-fix) fix your issue ?

**Comment by alex-phillips** [comment]
@massa84 Yup, it looks like that solution fixes it as well! Any estimate on when that might be merged?

**Pull request closed without merging**
