### PR TITLE
Various fixes in readme and beyond

### PR DESCRIPTION
**Pull request by wmcmurray**

### CODE REVIEW

**Comment by carpasse** [comment]
@wmcmurray I see this changes are included on your other PR https://github.com/MailOnline/videojs-vast-vpaid/pull/107, would it be ok to close this one and focus on that https://github.com/MailOnline/videojs-vast-vpaid/pull/107??

**Comment by wmcmurray** [comment]
@carpasse yep good idea !

**Comment by carpasse** [comment]
@wmcmurray There are some conflicts on the PR can you please rebase so we can merger it?

**Comment by wmcmurray** [comment]
There you go ! someone had already done some of my fixes, which caused conflicts

**Comment by carpasse** [comment]
@wmcmurray Thanks for the PR

**Pull request merged**
