### PR TITLE
fix iframe positioning

### PR DESCRIPTION
**Pull request by jdreetz**

### CODE REVIEW

**Comment by jdreetz** [comment]
Removing the margin and padding inside the ad iframe allows the ad content to be positioned left,top 0 without having to set 'position:absolute' on the container content. Setting the border to 'none' prevents the   inset border from displaying around the ad iframe.

**Comment by Fetz** [comment]
Hi @jdreetz, thank you for contribution.

But because that file is auto generated (and as well belongs to another repo),  your changes will be lost.

Please do the changes in this repo:
https://github.com/MailOnline/VPAIDHTML5Client

Please do the change in this file:
 - https://github.com/MailOnline/VPAIDHTML5Client/blob/master/js/iframe.template.html

- then run `gulp`

the html is being required by this file:
https://github.com/MailOnline/VPAIDHTML5Client/blob/master/js/VPAIDHTML5Client.js#L7

- confirm if in your machine this file has your changes:
https://github.com/MailOnline/VPAIDHTML5Client/blob/master/bin/VPAIDHTML5Client.js#L526

- if yes then please do pull request.

The reason is a different repo, is to allow to be independent of videojs, so if another person wants to use the code for a different player he can, and as well to simplify the code of the plugin.

**Comment by jdreetz** [comment]
Ok, I'll give that a try. Sorry for the misunderstanding @Fetz!

**Comment by jdreetz** [comment]
@Fetz - here's the PR for VPAIDHTML5Client - 
https://github.com/MailOnline/VPAIDHTML5Client/pull/3

**Comment by carpasse** [comment]
We have already merged the PR on VPAIDHTML5Client so I am closing this PR.
@Fetz please update the VPAIDHTML5Client version in the plugin once you have released.

**Pull request closed without merging**
