### PR TITLE
fix of `Cannot read property 'replace' of undefined` error

### PR DESCRIPTION
**Pull request by sanex3339**
fix for https://github.com/MailOnline/videojs-vast-vpaid/issues/223

### CODE REVIEW

**Comment by sanex3339** [comment]
ping

**Comment by sanex3339** [comment]
when i can expect new release with this PR?

**Comment by Fetz** [comment]
sorry I will do a release with this today

**Comment by sanex3339** [comment]
thank you

**Comment by Fetz** [comment]
@sanex3339 your fix was released https://github.com/MailOnline/videojs-vast-vpaid/commit/26141e91c52481343bbb73165fbdef5e03ebc383

**Pull request merged**
