### PR TITLE
Allow user to specify what mimeType mediaFile to load

### PR DESCRIPTION
**Pull request by joshmadewell**
I noticed that no matter what mediaFiles we got back from and adserver, we would try the first file in the array. This wasn't good for use because we use the same RON tag that might have a flash file returned (good for desktop, bad for mobile).

Having this feature allows us at runtime to tell the plugin which mimeType it should use when loading the ad manager.

Unit tests and readme updated for this feature:

#### preferredTech
Option to tell the plugin what type of mediaFile to open first. By default, the plugin will load the first supported mediaFile. This is a way to ensure HTML5 is loaded even if a .swf is the first option in the MediaFiles array (good for mobile).
```Defaults to undefined```

Available Options:

```flash``` which will attempt to load available ```application/x-shockwave-flash``` -or-

```html5``` which will attempt to load available ```application/javascript```

You can also pass in the mimeType itself if you'd like to be more explicit.

### CODE REVIEW

**Comment by qpre** [comment]
Please note that some providers still use tags such as `application/x-javascript`.

you can find an extensive list of the media types that javascript has used over the time ( :cry: ) [here](http://www.rfc-editor.org/rfc/rfc4329.txt)

**Comment by Fetz** [comment]
Hi @joshmadewell, thanks for your contribution now that I have access I can accept pull requests/etc.

When you have some time, can you fix the conflicts, and @qpre is a good point to include the other variations.

**Comment by joshmadewell** [comment]
@Fetz glad to have you back! 
@qpre I thought when I first saw your post, you had done the work for this in a pull request of your own? was I just seeing things?

**Comment by joshmadewell** [comment]
@Fetz  I've merged in the changes the @qpre made for this branch. Let me know if you need anything else from me to get this merged in. Thanks!

**Comment by jonathanbrenman** [comment]
I pass the mime preferredTech: "video/mp4", and its not working, 
still is bringing flv schockwave...

**Pull request merged**
